---
title: Lawrence Jones
email: me@lawrencejones.dev
description: |
  Working on building reliable infrastructure for GoCardless, a fast-growing
  fintech based in London. Focused on tackling infrastructure problems with a
  software engineering mindset.

# Don't use the default /yyyy/mm/dd/title permalink to avoid breaking links when
# you change publish date.
permalink: /:categories/:title/

url: "https://blog.lawrencejones.dev"
baseurl: ""
show_excerpts: true
google_analytics: UA-134680924-1
collections:
  - medium_posts

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-redirect-from

minima:
  social_links:
    twitter: lawrjone
    github: lawrencejones
